### ISSUE TITLE
question about the project

### ISSUE THREAD

**Issue by germal** [dan-ilc/person_tracking_project#2]
Hello @dan-ilc 

I am  interested on your project.Could you provide a description on how does it work ?
Thanks & regards
germal

**Comment by danmangles-srp** [comment]
Hi Germal,

Is there anything specific you would like to know? This is a basic
detect-then-track system consisting of 2 separate object detectors (one
vision, one LiDAR), an associator, and a tracker (based on a Kalman filter).

All the best,

Dan

**Comment by germal** [comment]
Hi Dan,
Thank you for your reply ! Yes , i would like to know if you can get a continous filtered pose estimation of the tracked object, using the image realsense camera 
Thanks a lot
germal

**Comment by danmangles-srp** [comment]
Hi,

I'm using a discrete time Extended Kalman Filter, so pose estimates are
only available at every iteration (set to 10Hz in ROS). So yes, depending
on your definition of continuous.

The information flow looks a bit like:

Camera : images -> Neural Network : detections -> associator : associated
detections -> kalman filter : pose estimates.

Let me know if this helps. If you're really interested, I can send you a
copy of my thesis for a full explanation although be warned it's 50 pages...

Dan

**Comment by germal** [comment]
Hello Dan,

You are very kind for sure I'd like to read your thesis.Have you applied it with a d435 ?

**Comment by germal** [comment]
Hello Dan @dan-ilc 
Please send me your thesis,I'd like to try your repo.
Regards

**Comment by dan-mangles-oxb** [comment]
Hey! Sure - email me on dan.mangles@oxbotica.com and I'll send it to you
