### ISSUE TITLE
setting a negative dimension to zero from bounding box

### ISSUE THREAD

**Issue by germal** [dan-ilc/person_tracking_project#3]
Hello Dan,
I've launched the detector node using the following  tf tree

map->odom-> camera_link ( d435)
As source of odometry I have a t265 , but I think this is irrelevant.
I've modified camera_camera link in your realsense_detector.py

 self.camera_base_frame = "camera_camera"
to 
 self.camera_base_frame = "camera_link"

and I commented out references to Velodyne in the tracker because I haven't ....The detector node throws this warning 

**!!!!!!setting a negative dimension to zero from bounding box**
_***********combined_callback()
RGB image has shape (480, 640)
Depth image has shape (480, 640)
image resized to 416x416, converted to numpy array and normalised to [0,1]
postprocessing() is getting the bounding boxes for an image of shape (480, 640, 3)
resized it to shape (416, 416, 3)
this bb is [243, -84, 481, 407]
depth shape is (480, 640)
get_bounding_boxes_from_rgb_msg() returned 1 bounding boxes 
update_pose_array_from_bounding_boxes()
**!!!!!!setting a negative dimension to zero from bounding box**
dist = 1.1757894736842105m
yaw = -0.071540, pitch = 0.084608
angle (0.5 (left) to -0.5 (right): -0.06562500000000004
local coord is [1.168586791034926, -0.08374356100040294, 0.09936203619219411]
adding pose at (0.500895, -1.219166, 0.154745) to the posearray
pose_array updated.
poses published to realsense_detections_poseArray_

and the tracker , after Kalman inizialization, throws this error , strange to me because the matrix F and GQG should be both 6x6 

mo_tracker_node: /usr/include/eigen3/Eigen/src/Core/Product.h:97: Eigen::Product<Lhs, Rhs, Option>::Product(const Lhs&, const Rhs&) [with _Lhs = Eigen::Matrix<double, -1, -1>; _Rhs = Eigen::Matrix<double, -1, 1>; int Option = 0; Eigen::Product<Lhs, Rhs, Option>::Lhs = Eigen::Matrix<double, -1, -1>; Eigen::Product<Lhs, Rhs, Option>::Rhs = Eigen::Matrix<double, -1, 1>]: Assertion `lhs.cols() == rhs.rows() && "invalid matrix product" && "if you wanted a coeff-wise or a dot product use the respective explicit functions"' 
rosrun multi_sensor_tracker mo_tracker_node

_Initiating tracker node
F: 
1 0 0 0 0 0
0 1 0 0 0 0
0 0 1 0 0 0
0 0 0 1 0 0
0 0 0 0 1 0
0 0 0 0 0 1
H: 
1 0 0 0 0 0
0 1 0 0 0 0
0 0 1 0 0 0
GQG: 
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
R_rgbd: 
7 0 0
0 7 0
0 0 7
P0: 
2 0 0 0 0 0
0 2 0 0 0 0
0 0 2 0 0 0
0 0 0 2 0 0
0 0 0 0 2 0
0 0 0 0 0 2
Calling MOTracker constructor
opening results file results_CSVs/res_01126_1131.csv
opening gnd file results_CSVs/gnd_01126_1131.csv
initialising grid map
t265_odom_framepose coords is 
 0.528115
 -1.04632
0.0806109
***********************************************
manageTracklets()
*******************************
There are 0 live tracklets,
There are 1 unpaired_detections
col_IDs:
row_IDs0
updateTrackletsWithCM()
********************************************************************************************
Assignment Algo: Average Runtime for this method: 6.3e-05s.

runtime for this mehthod is : 6.3e-05s.
********************************************************************************************
KalmanFilter constructor called
F: 
1 0 0 0 0 0
0 1 0 0 0 0
0 0 1 0 0 0
0 0 0 1 0 0
0 0 0 0 1 0
0 0 0 0 0 1
H: 
1 0 0 0 0 0
0 1 0 0 0 0
0 0 1 0 0 0
GQG: 
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
R: 
7 0 0
0 7 0
0 0 7
P: 
2 0 0 0 0 0
0 2 0 0 0 0
0 0 2 0 0 0
0 0 0 2 0 0
0 0 0 0 2 0
0 0 0 0 0 2
Tracklet constructor called
pose coords is 
0.488941
-1.15357
0.166838
***********************************************
manageTracklets()
*******************************
There are 1 live tracklets,
There are 1 unpaired_detections
0: tracklet_0
col_IDs:0
row_IDs0
updateTrackletsWithCM()
Min: 0.143086, at: 0,0
Tracklet::update()
pushed back new coord
tracklet vector 0 is paired
********************************************************************************************
Assignment Algo: Average Runtime for this method: 0.000355s.

runtime for this mehthod is : 0.000647s.
********************************************************************************************
pose coords is 
0.488441
-1.15549
0.148046
***********************************************
manageTracklets()
*******************************
There are 1 live tracklets,
There are 1 unpaired_detections
0: tracklet_0
col_IDs:0
row_IDs0
updateTrackletsWithCM()
Min: 0.0188962, at: 0,0
Tracklet::update()
pushed back new coord
tracklet vector 0 is paired
********************************************************************************************
Assignment Algo: Average Runtime for this method: 0.000295s.

runtime for this mehthod is : 0.000175s.
********************************************************************************************
pose coords is 
0.568228
-1.12857
0.110344
***********************************************
manageTracklets()
*******************************
There are 1 live tracklets,
There are 1 unpaired_detections
0: tracklet_0
col_IDs:0
row_IDs0
updateTrackletsWithCM()
Min: 0.0922619, at: 0,0
Tracklet::update()
pushed back new coord
tracklet vector 0 is paired
********************************************************************************************
Assignment Algo: Average Runtime for this method: 0.00026475s.

runtime for this mehthod is : 0.000174s.
********************************************************************************************
pose coords is 
 0.58297
-1.15316
0.084286
***********************************************
manageTracklets()
*******************************
There are 1 live tracklets,
There are 1 unpaired_detections
0: tracklet_0
col_IDs:0
row_IDs0
updateTrackletsWithCM()
Min: 0.0387464, at: 0,0
Tracklet::update()
pushed back new coord
tracklet vector 0 is paired
********************************************************************************************
Assignment Algo: Average Runtime for this method: 0.0002772s.

runtime for this mehthod is : 0.000327s.
********************************************************************************************
initialising Kalman Filter
P = 
2 0 0 0 0 0
0 2 0 0 0 0
0 0 2 0 0 0
0 0 0 2 0 0
0 0 0 0 2 0
0 0 0 0 0 2
F = 
1 0 0 0 0 0
0 1 0 0 0 0
0 0 1 0 0 0
0 0 0 1 0 0
0 0 0 0 1 0
0 0 0 0 0 1
pose coords is 
0.554496
-1.33052
 0.20038
***********************************************
manageTracklets()
*******************************
There are 1 live tracklets,
There are 1 unpaired_detections
0: tracklet_0
col_IDs:0
row_IDs0
updateTrackletsWithCM()
Min: 0.213874, at: 0,0
Tracklet::update()
pushed back new coord
predicting and updating kf for Tracklet_0
time =10.741
dt =2.13435
F =
      1       0       0 2.13435       0       0
      0       1       0       0 2.13435       0
      0       0       1       0       0 2.13435
      0       0       0       1       0       0
      0       0       0       0       1       0
      0       0       0       0       0       1
GQG =
42.6869       0       0       0       0       0
      0 42.6869       0       0       0       0
      0       0 42.6869       0       0       0
      0       0       0 42.6869       0       0
      0       0       0       0 42.6869       0
      0       0       0       0       0 42.6869
mo_tracker_node: /usr/include/eigen3/Eigen/src/Core/Product.h:97: Eigen::Product<Lhs, Rhs, Option>::Product(const Lhs&, const Rhs&) [with _Lhs = Eigen::Matrix<double, -1, -1>; _Rhs = Eigen::Matrix<double, -1, 1>; int Option = 0; Eigen::Product<Lhs, Rhs, Option>::Lhs = Eigen::Matrix<double, -1, -1>; Eigen::Product<Lhs, Rhs, Option>::Rhs = Eigen::Matrix<double, -1, 1>]: Assertion `lhs.cols() == rhs.rows() && "invalid matrix product" && "if you wanted a coeff-wise or a dot product use the respective explicit functions"' failed.

@dan-ilc,@dan-mangles-oxb could you please advice ?
Thanks 
Regards
germal

**Comment by danmangles-srp** [comment]
Are you running in debug or release? Try switching?

**Comment by germal** [comment]
Hey Dan
Just trying to build in debug , I will let you know soon
thanks

**Comment by germal** [comment]
Hi Dan
building in Release mode the error  related to dimension checking **disappear**, but I don't understand why was triggered if Matrix1(columns)=Matrix2(rows) . Could you advice ?
Thanks  & Regards

**Comment by danmangles-srp** [comment]
It's a great question, but I'd need to look closer at the matrix math to
check. Possibly an Eigen bug.

Dan

**Comment by germal** [comment]
Thank you Dan, your project is really cool and run fast on my jetson , I will try to understand deeply the code.
Cheers
gian
